### PR TITLE
Add support for in-cluster-config.

### PR DESCRIPTION
**Pull request by mikkeloscar**
Makes it possible to omit the `--kubernetes-server` flag when using the
kubernetes producer and instead rely on in-cluster-configuration based on
the environment. This obsoletes the need for running a hyperkube image as
sidecar and using `kubectl proxy` to connect to the API.

First commit is without the vendoring.

### CODE REVIEW

**Comment by Raffo** [comment]
👍

**Comment by linki** [comment]
LGTM

**Comment by ideahitme** [comment]
👍

**Comment by mikkeloscar** [comment]
@ideahitme you mentioned some issue in the standup?

**Comment by ideahitme** [comment]
@mikkeloscar yup, sorry got some issue with my local cluster :( all good :)

**Pull request merged**
