### PR TITLE
update mate to v0.3.2

### PR DESCRIPTION
**Pull request by linki**
@ideahitme as it contains quite a significant bug fix for Google I would like to get rid of the old version in the docs.

### CODE REVIEW

**Comment by ideahitme** [comment]
@linki maybe u can update the one in `example/aws/` as well

**Comment by linki** [comment]
@ideahitme done. also made the jump to `v0.3.2` right away.

**Comment by ideahitme** [comment]
👍

**Comment by linki** [comment]
are we missing a mutex somewhere? https://travis-ci.org/zalando-incubator/mate/jobs/188595504

**Comment by ideahitme** [comment]
yup there is a missing mutex in the testing client https://github.com/zalando-incubator/mate/blob/master/pkg/aws/test/test_client.go#L72. Let me create a fix

**Pull request merged**
