### PR TITLE
Feature/aws nginx notes

### PR DESCRIPTION
**Pull request by snoby**
Edited the Readme file to describe what changes need to be made to get the correct IP address with mate and an nginx ingress controller on AWS.

### CODE REVIEW

**Comment by szuecs** [comment]
Thanks for your PR

**Comment by szuecs** [comment]
@snoby Can you move your section just before "## Permissions" ?
I think the "Your Ingress controller should provision a Load Balancer (both ELB and ALB are supported by Mate)" part is more general than having it in the nginx ingress section.

**Comment by szuecs** [comment]
:+1:

**Comment by ideahitme** [comment]
thanks for help 👍

**Pull request merged**
